/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
package GUI;

import Models.Deelnemer;

/**
 *
 * @author Nick
 */
public class DeelnemerBekijken extends javax.swing.JFrame {

    /**
     * Creates new form DeelnemerBekijken
     */
    
    Deelnemer deelnemer;
    String is_bekend_uitvoer;
    
    public DeelnemerBekijken() {
        initComponents();
    }
    
    public DeelnemerBekijken(Deelnemer deelnemer)
    {
        initComponents();
        this.deelnemer = deelnemer;
        fillTextArea();
    }
    
    private void fillTextArea()
    {
        String voornaam = deelnemer.getVoornaam();
        String achternaam = deelnemer.getAchternaam();
        String straat = deelnemer.getStraat();
        String huisnummer = Integer.toString(deelnemer.getHuisnummer());
        String postcode = deelnemer.getPostcode();
        String woonplaats = deelnemer.getWoonplaats();
        String tel_nr = Integer.toString(deelnemer.getTelefoon());
        String email = deelnemer.getEmail();
        String is_bekend = deelnemer.getIsbekend();
        String rating = Integer.toString(deelnemer.getRating());
        
        if("j".equals(is_bekend))
        {
           is_bekend_uitvoer = "Ja";
        }
        
        else if("n".equals(is_bekend))
        {
            is_bekend_uitvoer = "Nee";
        }
        else
        {
            is_bekend_uitvoer = "";
        }
        
        TextArea_Gegevens.setText("Voornaam :\t" + voornaam + "\n" +
                                  "Achternaam :\t" + achternaam + "\n" +
                                  "Straat :\t" + straat + "\n" +
                                  "Huisnummer :\t" + huisnummer + "\n" +
                                  "Postcode :\t" + postcode + "\n" +
                                  "Woonplaats :\t" + woonplaats + "\n" +
                                  "Telefoon :\t" + tel_nr + "\n" +
                                  "Email :\t" + email +"\n" +
                                  "Bekend :\t" + is_bekend_uitvoer + "\n" +
                                  "Rating :\t" +rating + "\n");
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        TextArea_Gegevens = new javax.swing.JTextArea();
        Button_Back = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        TextArea_Gegevens.setColumns(20);
        TextArea_Gegevens.setRows(5);
        jScrollPane1.setViewportView(TextArea_Gegevens);

        Button_Back.setText("Back");
        Button_Back.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Button_BackActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 380, Short.MAX_VALUE)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(Button_Back)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 247, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(Button_Back)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void Button_BackActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Button_BackActionPerformed
        this.dispose();
    }//GEN-LAST:event_Button_BackActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /*
         * Set the Nimbus look and feel
         */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /*
         * If Nimbus (introduced in Java SE 6) is not available, stay with the
         * default look and feel. For details see
         * http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(DeelnemerBekijken.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(DeelnemerBekijken.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(DeelnemerBekijken.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(DeelnemerBekijken.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /*
         * Create and display the form
         */
        java.awt.EventQueue.invokeLater(new Runnable() {

            public void run() {
                new DeelnemerBekijken().setVisible(true);
            }
        });
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton Button_Back;
    private javax.swing.JTextArea TextArea_Gegevens;
    private javax.swing.JScrollPane jScrollPane1;
    // End of variables declaration//GEN-END:variables
}
