/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
package GUI;

import configuration.SimpleDataSourceV2;
import java.awt.Color;
import java.sql.Connection;
import java.sql.PreparedStatement;
import javax.swing.ButtonGroup;
import javax.swing.JOptionPane;
import utils.EmailAddressValidator;

/**
 *
 * @author arjan
 */
public class DeelnemerToevoegen extends javax.swing.JFrame {

    /**
     * Creates new form DeelnemerToevoegen
     */
    private boolean checkPostcode;
    private boolean checkEmail;

    public DeelnemerToevoegen() {
        initComponents();
        FillComponents();
        checkEmail = false;
        checkPostcode = false;
    }

    private void FillComponents() {
        ButtonGroup bekend = new ButtonGroup();
        bekend.add(RadioButton_BekendJa);
        bekend.add(RadioButton_BekendNee);
    }

    private void checkEmail(String email) {
        if (EmailAddressValidator.isValidEmailAddress(email) == true) {
            this.lbMeldingEmail.setForeground(Color.green);
            this.lbMeldingEmail.setText("Email - Juiste formaat");
            checkEmail = true;
        } else {
            this.lbMeldingEmail.setForeground(Color.red);
            this.lbMeldingEmail.setText("Email - fout formaat");
            checkEmail = false;
        }
    }

    private void checkPostcode(String postcode) {


        String pattern = "[0-9]{4}\\s[a-zA-z]{2}";

        if (postcode.matches(pattern)) {
            this.lbMelding.setForeground(Color.green);
            this.lbMelding.setText("Postcode - juiste formaat");
            checkPostcode = true;
        } else {
            this.lbMelding.setForeground(Color.red);
            this.lbMelding.setText("Postcode - foute formaat");
            checkPostcode = false;
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jButton1 = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        TextField_Voornaam = new javax.swing.JTextField();
        TextField_Achternaam = new javax.swing.JTextField();
        TextField_Straat = new javax.swing.JTextField();
        TextField_Huisnummer = new javax.swing.JTextField();
        TextField_Postcode = new javax.swing.JTextField();
        TextField_Woonplaats = new javax.swing.JTextField();
        TextField_Telefoonnummer = new javax.swing.JTextField();
        TextField_Email = new javax.swing.JTextField();
        RadioButton_BekendJa = new javax.swing.JRadioButton();
        RadioButton_BekendNee = new javax.swing.JRadioButton();
        Button_Toevoegen = new javax.swing.JButton();
        Button_Back = new javax.swing.JButton();
        lbMelding = new javax.swing.JLabel();
        lbMeldingEmail = new javax.swing.JLabel();

        jButton1.setText("jButton1");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setText("Voornaam:");

        jLabel2.setText("Achternaam:");

        jLabel3.setText("Straat:");

        jLabel4.setText("Huisnummer:");

        jLabel5.setText("Postcode:");

        jLabel6.setText("Woonplaats:");

        jLabel7.setText("Telefoon Nummer:");

        jLabel8.setText("Email:");

        jLabel9.setText("Bekend");

        TextField_Postcode.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                TextField_PostcodeKeyReleased(evt);
            }
        });

        TextField_Email.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                TextField_EmailKeyReleased(evt);
            }
        });

        RadioButton_BekendJa.setText("Ja");

        RadioButton_BekendNee.setText("Nee");

        Button_Toevoegen.setText("Toevoegen");
        Button_Toevoegen.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Button_ToevoegenActionPerformed(evt);
            }
        });

        Button_Back.setText("Back");
        Button_Back.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Button_BackActionPerformed(evt);
            }
        });

        org.jdesktop.layout.GroupLayout layout = new org.jdesktop.layout.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(layout.createSequentialGroup()
                .addContainerGap()
                .add(layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
                    .add(org.jdesktop.layout.GroupLayout.TRAILING, layout.createSequentialGroup()
                        .add(Button_Back)
                        .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED, 165, Short.MAX_VALUE)
                        .add(Button_Toevoegen))
                    .add(layout.createSequentialGroup()
                        .add(layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
                            .add(jLabel4)
                            .add(jLabel3)
                            .add(jLabel2)
                            .add(jLabel1))
                        .add(32, 32, 32)
                        .add(layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
                            .add(TextField_Voornaam)
                            .add(TextField_Achternaam)
                            .add(TextField_Straat)))
                    .add(layout.createSequentialGroup()
                        .add(jLabel9)
                        .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
                        .add(RadioButton_BekendJa)
                        .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
                        .add(RadioButton_BekendNee))
                    .add(layout.createSequentialGroup()
                        .add(layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
                            .add(jLabel7)
                            .add(jLabel6)
                            .add(jLabel8)
                            .add(jLabel5))
                        .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
                        .add(layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
                            .add(TextField_Postcode, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 74, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                            .add(layout.createParallelGroup(org.jdesktop.layout.GroupLayout.TRAILING, false)
                                .add(TextField_Telefoonnummer)
                                .add(org.jdesktop.layout.GroupLayout.LEADING, TextField_Woonplaats, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, 213, Short.MAX_VALUE)
                                .add(org.jdesktop.layout.GroupLayout.LEADING, TextField_Email)
                                .add(org.jdesktop.layout.GroupLayout.LEADING, lbMeldingEmail, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .add(lbMelding, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                            .add(TextField_Huisnummer))))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(layout.createSequentialGroup()
                .addContainerGap()
                .add(layout.createParallelGroup(org.jdesktop.layout.GroupLayout.BASELINE)
                    .add(jLabel1)
                    .add(TextField_Voornaam, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
                .add(layout.createParallelGroup(org.jdesktop.layout.GroupLayout.BASELINE)
                    .add(jLabel2)
                    .add(TextField_Achternaam, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
                .add(layout.createParallelGroup(org.jdesktop.layout.GroupLayout.BASELINE)
                    .add(jLabel3)
                    .add(TextField_Straat, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
                .add(layout.createParallelGroup(org.jdesktop.layout.GroupLayout.BASELINE)
                    .add(jLabel4)
                    .add(TextField_Huisnummer, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
                .add(layout.createParallelGroup(org.jdesktop.layout.GroupLayout.BASELINE)
                    .add(jLabel5)
                    .add(TextField_Postcode, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE))
                .add(8, 8, 8)
                .add(lbMelding, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 19, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
                .add(layout.createParallelGroup(org.jdesktop.layout.GroupLayout.BASELINE)
                    .add(jLabel6)
                    .add(TextField_Woonplaats, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
                .add(layout.createParallelGroup(org.jdesktop.layout.GroupLayout.BASELINE)
                    .add(jLabel7)
                    .add(TextField_Telefoonnummer, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
                .add(layout.createParallelGroup(org.jdesktop.layout.GroupLayout.BASELINE)
                    .add(jLabel8)
                    .add(TextField_Email, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE))
                .add(5, 5, 5)
                .add(lbMeldingEmail, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, 20, Short.MAX_VALUE)
                .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
                .add(layout.createParallelGroup(org.jdesktop.layout.GroupLayout.BASELINE)
                    .add(jLabel9)
                    .add(RadioButton_BekendJa)
                    .add(RadioButton_BekendNee))
                .add(18, 18, 18)
                .add(layout.createParallelGroup(org.jdesktop.layout.GroupLayout.BASELINE)
                    .add(Button_Toevoegen)
                    .add(Button_Back))
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void Button_ToevoegenActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Button_ToevoegenActionPerformed



        if (checkEmail == true && checkPostcode == true) {

            //Strings om de inhoud van de textfields op te halen. 
            try {
                String voornaam = TextField_Voornaam.getText();
                String achternaam = TextField_Achternaam.getText();
                String straat = TextField_Straat.getText();
                int huisnummer = Integer.parseInt(TextField_Huisnummer.getText());
                String postcode = TextField_Postcode.getText();
                String woonplaats = TextField_Woonplaats.getText();
                int telnr = Integer.parseInt(TextField_Telefoonnummer.getText());
                String email = TextField_Email.getText();
                String bekend = null;

                //checks which radiobutton is selected. if none, show messagedialog saying"select something".

                if (RadioButton_BekendJa.isSelected()) {
                    bekend = "j";
                } else if (RadioButton_BekendNee.isSelected()) {
                    bekend = "n";
                } else {
                    JOptionPane.showMessageDialog(this, "Selecteer de status van 'bekend'");
                }


                // SQL string

                String sql = "insert into Deelnemer(voornaam, achternaam, straat, huisnummer, postcode, woonplaats, tel_nr, e_mailadres, is_bekend) values(?,?,?,?,?,?,?,?,?)";


                try {
                    Connection conn = SimpleDataSourceV2.getConnection();
                    PreparedStatement stat = conn.prepareStatement(sql);

                    //Sets the variables in sql statement

                    stat.setString(1, voornaam);
                    stat.setString(2, achternaam);
                    stat.setString(3, straat);
                    stat.setInt(4, huisnummer);
                    stat.setString(5, postcode);
                    stat.setString(6, woonplaats);
                    stat.setInt(7, telnr);
                    stat.setString(8, email);
                    stat.setString(9, bekend);

                    stat.execute();

                    new DeelnemerBeheer().setVisible(true);
                    this.dispose();

                } catch (Exception e) {
                    JOptionPane.showMessageDialog(this, e);
                }

            } catch (NumberFormatException ex) {
                JOptionPane.showMessageDialog(this, ex);
            }
        } else {
            JOptionPane.showMessageDialog(this, "De gegevens van Postcode of Email zijn incorrect.");
        }

    }//GEN-LAST:event_Button_ToevoegenActionPerformed

    private void Button_BackActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Button_BackActionPerformed
        // Open DeelnemerBeheer
        new DeelnemerBeheer().setVisible(true);
        // Close current Window
        this.dispose();
    }//GEN-LAST:event_Button_BackActionPerformed

    private void TextField_PostcodeKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_TextField_PostcodeKeyReleased
        String postCode = this.TextField_Postcode.getText();
        checkPostcode(postCode);
    }//GEN-LAST:event_TextField_PostcodeKeyReleased

    private void TextField_EmailKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_TextField_EmailKeyReleased
        String email = this.TextField_Email.getText();
        checkEmail(email);

    }//GEN-LAST:event_TextField_EmailKeyReleased

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /*
         * Set the Nimbus look and feel
         */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /*
         * If Nimbus (introduced in Java SE 6) is not available, stay with the
         * default look and feel. For details see
         * http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(DeelnemerToevoegen.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(DeelnemerToevoegen.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(DeelnemerToevoegen.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(DeelnemerToevoegen.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /*
         * Create and display the form
         */
        java.awt.EventQueue.invokeLater(new Runnable() {

            public void run() {
                new DeelnemerToevoegen().setVisible(true);
            }
        });
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton Button_Back;
    private javax.swing.JButton Button_Toevoegen;
    private javax.swing.JRadioButton RadioButton_BekendJa;
    private javax.swing.JRadioButton RadioButton_BekendNee;
    private javax.swing.JTextField TextField_Achternaam;
    private javax.swing.JTextField TextField_Email;
    private javax.swing.JTextField TextField_Huisnummer;
    private javax.swing.JTextField TextField_Postcode;
    private javax.swing.JTextField TextField_Straat;
    private javax.swing.JTextField TextField_Telefoonnummer;
    private javax.swing.JTextField TextField_Voornaam;
    private javax.swing.JTextField TextField_Woonplaats;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JLabel lbMelding;
    private javax.swing.JLabel lbMeldingEmail;
    // End of variables declaration//GEN-END:variables
}
