/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
package GUI;

import Models.Deelnemer;
import Models.Toernooi;
import configuration.SimpleDataSourceV2;
import java.awt.Color;
import java.sql.Connection;
import java.sql.Date;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.util.Calendar;
import javax.swing.ButtonGroup;
import javax.swing.JOptionPane;
import utils.DateUtil;

/**
 *
 * @author Nick
 */
public class DeelnemerWijzigenToernooien extends javax.swing.JFrame {

    /**
     * Creates new form DeelnemerWijzigenToernooien
     */
    Deelnemer deelnemer;
    Toernooi toernooi;
    private Date datum;
    private int d_code;
    private int t_code;
    private String betaald;
    private boolean checkInvoer;
    private boolean dagCheck;
    private boolean maandCheck;
    private boolean jaarCheck;

    public DeelnemerWijzigenToernooien() {
        initComponents();
    }

    public DeelnemerWijzigenToernooien(Deelnemer deelnemer, Toernooi toernooi) {
        initComponents();

        ButtonGroup button = new ButtonGroup();
        button.add(rbJa);
        button.add(rbNee);

        this.deelnemer = deelnemer;
        this.toernooi = toernooi;

        String naam = deelnemer.getVoornaam() + " " + deelnemer.getAchternaam();
        String toernooinummer = Integer.toString(toernooi.getT_Code());

        lbDeelnemer.setText(naam);
        lbToernooi.setText(toernooinummer);
        initValues();
        radioButtonCheck();

        if (tfDag.isVisible()) {

            java.util.Calendar cal = java.util.Calendar.getInstance();
            cal.clear();
            cal.setTime(datum);
            int jaar = cal.get(Calendar.YEAR);
            int maand = cal.get(Calendar.MONTH);
            int dag = cal.get(Calendar.DAY_OF_MONTH);
            maand++;

            String JAAR = Integer.toString(jaar);
            String MAAND = Integer.toString(maand);
            String DAG = Integer.toString(dag);

            tfJaar.setText(JAAR);
            tfMaand.setText(MAAND);
            tfDag.setText(DAG);
        }


    }

    private void radioButtonCheck() {
        if (rbNee.isSelected()) {
            tfDag.setVisible(false);
            tfMaand.setVisible(false);
            tfJaar.setVisible(false);
            jLabel4.setVisible(false);
        } else if (rbJa.isSelected()) {
            tfDag.setVisible(true);
            tfMaand.setVisible(true);
            tfJaar.setVisible(true);
            jLabel4.setVisible(true);
        } else {
            tfDag.setVisible(false);
            tfMaand.setVisible(false);
            tfJaar.setVisible(false);
            jLabel4.setVisible(false);
        }
    }

    private void initValues() {
        t_code = toernooi.getT_Code();
        d_code = deelnemer.getD_code();

        String sql = "Select * from heeft_betaald where t_code = ? and d_code = ?";

        try {

            Connection conn = SimpleDataSourceV2.getConnection();
            PreparedStatement stat = conn.prepareStatement(sql);
            stat.setInt(1, t_code);
            stat.setInt(2, d_code);
            ResultSet res = stat.executeQuery();
            while (res.next()) {
                betaald = res.getString("inleggeld_betaald");
                datum = res.getDate("datum_betaling");
            }

        } catch (Exception e) {
            System.out.println(e);
        }

        if ("j".equals(betaald)) {
            rbJa.setSelected(true);
            dagCheck = true;
            maandCheck = true;
            jaarCheck = true;
        } else if ("n".equals(betaald)) {
            rbNee.setSelected(true);
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        lbDeelnemer = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        lbToernooi = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        rbJa = new javax.swing.JRadioButton();
        rbNee = new javax.swing.JRadioButton();
        jLabel4 = new javax.swing.JLabel();
        tfDag = new javax.swing.JTextField();
        tfMaand = new javax.swing.JTextField();
        tfJaar = new javax.swing.JTextField();
        btBack = new javax.swing.JButton();
        btWijzigen = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setText("Deelnemer : ");

        jLabel2.setText("Toernooi : ");

        jLabel3.setText("Heeft Betaald : ");

        rbJa.setText("Ja");
        rbJa.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rbJaActionPerformed(evt);
            }
        });

        rbNee.setText("Nee");
        rbNee.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rbNeeActionPerformed(evt);
            }
        });

        jLabel4.setText("Datum (DD/MM/YYYY) :");

        tfDag.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                tfDagKeyReleased(evt);
            }
        });

        tfMaand.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                tfMaandKeyReleased(evt);
            }
        });

        tfJaar.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                tfJaarKeyReleased(evt);
            }
        });

        btBack.setText("Back");
        btBack.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btBackActionPerformed(evt);
            }
        });

        btWijzigen.setText("Wijzigen");
        btWijzigen.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btWijzigenActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel1)
                                .addGap(18, 18, 18)
                                .addComponent(lbDeelnemer))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel2)
                                .addGap(18, 18, 18)
                                .addComponent(lbToernooi))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel3)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(rbNee)
                                    .addComponent(rbJa)))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel4)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(tfDag, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(tfMaand, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(tfJaar, javax.swing.GroupLayout.PREFERRED_SIZE, 72, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(0, 38, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(btWijzigen)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(btBack, javax.swing.GroupLayout.PREFERRED_SIZE, 58, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(lbDeelnemer))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(lbToernooi))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(rbJa))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(rbNee)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(tfDag, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(tfMaand, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(tfJaar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 52, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btBack)
                    .addComponent(btWijzigen))
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void rbJaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rbJaActionPerformed
        radioButtonCheck();
    }//GEN-LAST:event_rbJaActionPerformed

    private void rbNeeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rbNeeActionPerformed
        radioButtonCheck();
    }//GEN-LAST:event_rbNeeActionPerformed

    private void btBackActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btBackActionPerformed
        new DeelnemerBekijkToernooien(deelnemer).setVisible(true);
        this.dispose();
    }//GEN-LAST:event_btBackActionPerformed

    private void btWijzigenActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btWijzigenActionPerformed
        checkInvoer = true;
        if (tfDag.isVisible()) {
            try {
                int dag = Integer.parseInt(tfDag.getText());
                int maand = Integer.parseInt(tfMaand.getText());
                int jaar = Integer.parseInt(tfJaar.getText());

                datum = DateUtil.toSqlDate(jaar, maand, dag);
            } catch (NumberFormatException e) {
                JOptionPane.showMessageDialog(this, "Voer gehele getallen in bij datum.");
                checkInvoer = false;
            }
            betaald = "j";
        } else {
            datum = null;
            betaald = "n";
            dagCheck = true;
            maandCheck = true;
            jaarCheck = true;
        }


        String sql = "Update heeft_betaald set datum_betaling=?, inleggeld_betaald=? where d_code = ? and t_code = ?";

        if (checkInvoer != false && dagCheck != false && maandCheck != false && jaarCheck != false) {

            try {
                Connection conn = SimpleDataSourceV2.getConnection();
                PreparedStatement stat = conn.prepareStatement(sql);
                stat.setDate(1, datum);
                stat.setString(2, betaald);
                stat.setInt(3, d_code);
                stat.setInt(4, t_code);
                stat.execute();

                new DeelnemerBekijkToernooien(deelnemer).setVisible(true);
                this.dispose();

            } catch (Exception e) {
                System.out.println(e);
            }
        } else if (dagCheck == false || maandCheck == false || jaarCheck == false) {
            JOptionPane.showMessageDialog(this, "De gegevens van datum_betaald zijn incorrect.");
        }
    }//GEN-LAST:event_btWijzigenActionPerformed

    private void tfDagKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_tfDagKeyReleased
        String pattern = "[0-9]{2}";

        if (tfDag.getText().matches(pattern)) {
            tfDag.setBackground(Color.green);
            dagCheck = true;
        } else {
            tfDag.setBackground(Color.RED);
            dagCheck = false;
        }
    }//GEN-LAST:event_tfDagKeyReleased

    private void tfMaandKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_tfMaandKeyReleased
        String pattern = "[0-9]{2}";

        if (tfMaand.getText().matches(pattern)) {
            tfMaand.setBackground(Color.green);
            maandCheck = true;
        } else {
            tfMaand.setBackground(Color.RED);
            maandCheck = false;
        }
    }//GEN-LAST:event_tfMaandKeyReleased

    private void tfJaarKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_tfJaarKeyReleased
        String pattern = "[0-9]{4}";

        if (tfJaar.getText().matches(pattern)) {
            tfJaar.setBackground(Color.green);
            jaarCheck = true;
        } else {
            tfJaar.setBackground(Color.RED);
            jaarCheck = false;
        }
    }//GEN-LAST:event_tfJaarKeyReleased

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /*
         * Set the Nimbus look and feel
         */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /*
         * If Nimbus (introduced in Java SE 6) is not available, stay with the
         * default look and feel. For details see
         * http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(DeelnemerWijzigenToernooien.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(DeelnemerWijzigenToernooien.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(DeelnemerWijzigenToernooien.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(DeelnemerWijzigenToernooien.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /*
         * Create and display the form
         */
        java.awt.EventQueue.invokeLater(new Runnable() {

            public void run() {
                new DeelnemerWijzigenToernooien().setVisible(true);
            }
        });
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btBack;
    private javax.swing.JButton btWijzigen;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel lbDeelnemer;
    private javax.swing.JLabel lbToernooi;
    private javax.swing.JRadioButton rbJa;
    private javax.swing.JRadioButton rbNee;
    private javax.swing.JTextField tfDag;
    private javax.swing.JTextField tfJaar;
    private javax.swing.JTextField tfMaand;
    // End of variables declaration//GEN-END:variables
}
