/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
package GUI;

import Models.Faciliteit;
import configuration.SimpleDataSourceV2;
import java.awt.Color;
import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.SQLException;
import javax.swing.JOptionPane;

/**
 *
 * @author Josua
 */
public class FaciliteitWijzigen extends javax.swing.JFrame {
    
    private boolean PostcodeCheck;

    /**
     * Creates new form FaciliteitWijzigen
     */
    
    Faciliteit faciliteit;
    
    public FaciliteitWijzigen() {
        initComponents();
        initModels();
        PostcodeCheck = false;
    }
    
    public FaciliteitWijzigen(Faciliteit faciliteit) {
        this.faciliteit=faciliteit;
        initComponents();
        initModels();
    }
    
    private void initModels() {
        
     TextField_Naam.setText(faciliteit.getNaam());
     TextField_Straatnaam.setText(faciliteit.getStraat());
     TextField_Huisnummer.setText(faciliteit.getHuisnummer());
     TextField_Postcode.setText(faciliteit.getPostcode());
     TextField_Plaats.setText(faciliteit.getPlaats());
     TextField_MaxAantalSpelers.setText("" + faciliteit.getMax_aantal());
    
    }

    private void PostcodeCheck(String postcode){
        
           
       String pattern = "[0-9]{4}[a-zA-z]{2}";
        
       if(postcode.matches(pattern)){
            this.Label_PostcodeCheck.setForeground(Color.green);
            this.Label_PostcodeCheck.setText("Postcode is in het juiste formaat");
            PostcodeCheck = true;
       }else{
           this.Label_PostcodeCheck.setForeground(Color.red);
            this.Label_PostcodeCheck.setText("Postcode is niet juist(1234AZ)");
            PostcodeCheck = false;
            
       }
       
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        TextField_Huisnummer = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        TextField_Naam = new javax.swing.JTextField();
        TextField_Straatnaam = new javax.swing.JTextField();
        Button_Back = new javax.swing.JButton();
        jLabel3 = new javax.swing.JLabel();
        TextField_MaxAantalSpelers = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        TextField_Plaats = new javax.swing.JTextField();
        TextField_Postcode = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        Button_Wijzigen = new javax.swing.JButton();
        Label_PostcodeCheck = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setText("Naam");

        Button_Back.setText("Back");
        Button_Back.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Button_BackActionPerformed(evt);
            }
        });

        jLabel3.setText("Max. aantal spelers");

        jLabel4.setText("Postcode");

        TextField_Postcode.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                TextField_PostcodeKeyReleased(evt);
            }
        });

        jLabel2.setText("Straatnaam en  Huisnr.");

        Button_Wijzigen.setText("Wijzigen");
        Button_Wijzigen.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Button_WijzigenActionPerformed(evt);
            }
        });

        jLabel5.setText("Plaats");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(Button_Back)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(Button_Wijzigen)
                        .addContainerGap())
                    .addGroup(layout.createSequentialGroup()
                        .addGap(0, 30, Short.MAX_VALUE)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel2)
                            .addComponent(jLabel4)
                            .addComponent(jLabel1)
                            .addComponent(jLabel5)
                            .addComponent(jLabel3))
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(TextField_MaxAantalSpelers, javax.swing.GroupLayout.PREFERRED_SIZE, 54, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(TextField_Straatnaam, javax.swing.GroupLayout.PREFERRED_SIZE, 130, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                        .addComponent(TextField_Huisnummer, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addComponent(TextField_Plaats, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(59, 59, 59))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addComponent(TextField_Naam, javax.swing.GroupLayout.PREFERRED_SIZE, 210, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(60, 60, 60))
                            .addGroup(layout.createSequentialGroup()
                                .addGap(6, 6, 6)
                                .addComponent(TextField_Postcode, javax.swing.GroupLayout.PREFERRED_SIZE, 54, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(Label_PostcodeCheck, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addContainerGap())))))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(32, 32, 32)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(TextField_Naam, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel1))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(TextField_Straatnaam, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(TextField_Huisnummer, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel2))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(TextField_Postcode, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jLabel4))
                    .addComponent(Label_PostcodeCheck, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 16, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(TextField_Plaats, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel5))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(TextField_MaxAantalSpelers, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel3))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(Button_Back)
                    .addComponent(Button_Wijzigen))
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void Button_BackActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Button_BackActionPerformed
        // Open DeelnemerBeheer
        new FaciliteitBeheer().setVisible(true);
        // Sluit huidig scherm
        this.dispose();
    }//GEN-LAST:event_Button_BackActionPerformed

    private void Button_WijzigenActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Button_WijzigenActionPerformed
        
        if (PostcodeCheck == true)  {
        try {
           
            
             //Connectie opvragen
            Connection conn = SimpleDataSourceV2.getConnection();

            //(Prepared)SQL statement opbouwen
            PreparedStatement preparedStatement = conn.prepareStatement("update Faciliteit set naam=?, Straatnaam=?, huisnummer=?, postcode=?, Max_aantal_spelers=?, plaats=? where f_code=? ");
            
            preparedStatement.setString(1, TextField_Naam.getText());
            preparedStatement.setString(2, TextField_Straatnaam.getText());
            preparedStatement.setString(3, TextField_Huisnummer.getText());
            preparedStatement.setString(4, TextField_Postcode.getText());
            preparedStatement.setInt(5, Integer.parseInt(TextField_MaxAantalSpelers.getText()));
            preparedStatement.setString(6, TextField_Plaats.getText());
            preparedStatement.setInt(7, faciliteit.getF_code());
            //SQL statement uitvoeren
            preparedStatement.execute();

            //huidige scherm sluiten
            this.dispose();

            //Hoofdscherm opnieuw openen
            new FaciliteitBeheer().setVisible(true);



        } catch (SQLException ex) {
            JOptionPane.showMessageDialog(this, "Database error:" + ex.toString());
        } catch (NumberFormatException e) {
            JOptionPane.showMessageDialog(this, "vul alle velden in!");
        }
        }
    }//GEN-LAST:event_Button_WijzigenActionPerformed

    private void TextField_PostcodeKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_TextField_PostcodeKeyReleased
       //checkPostcode is checked whenever a character is added to the textfield.
        String postCode = this.TextField_Postcode.getText();
        PostcodeCheck(postCode);
    }//GEN-LAST:event_TextField_PostcodeKeyReleased

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /*
         * Set the Nimbus look and feel
         */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /*
         * If Nimbus (introduced in Java SE 6) is not available, stay with the
         * default look and feel. For details see
         * http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(FaciliteitWijzigen.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(FaciliteitWijzigen.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(FaciliteitWijzigen.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(FaciliteitWijzigen.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /*
         * Create and display the form
         */
        java.awt.EventQueue.invokeLater(new Runnable() {

            public void run() {
                new FaciliteitWijzigen().setVisible(true);
            }
        });
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton Button_Back;
    private javax.swing.JButton Button_Wijzigen;
    private javax.swing.JLabel Label_PostcodeCheck;
    private javax.swing.JTextField TextField_Huisnummer;
    private javax.swing.JTextField TextField_MaxAantalSpelers;
    private javax.swing.JTextField TextField_Naam;
    private javax.swing.JTextField TextField_Plaats;
    private javax.swing.JTextField TextField_Postcode;
    private javax.swing.JTextField TextField_Straatnaam;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    // End of variables declaration//GEN-END:variables
}
