/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
package GUI;

import Models.MasterclassZoeken;
import configuration.SimpleDataSourceV2;
import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.util.Calendar;
import java.sql.Date;
import javax.swing.DefaultComboBoxModel;
import javax.swing.JOptionPane;
import utils.DateUtil;

/**
 *
 * @author Otto
 */
public class MasterclassWijzigen extends javax.swing.JFrame {
MasterclassZoeken masterclass;
int M_Code;
Date Datum;
double Prijs;
int Minimale_rating;
int Docent;
int Locatie;
int jaar;
int maand;
int dag;
String Achternaam;
String LNaam;
        
        
    /**
     * Creates new form MasterclassWijzigen
     */
    public MasterclassWijzigen() {
        initComponents();

        vulDocent();
        vulLocatie();
    }
    public MasterclassWijzigen(MasterclassZoeken masterclass){
        initComponents();

        vulDocent();
        vulLocatie();
        this.masterclass = masterclass;
        M_Code = masterclass.getM_Code();
        
        String prijs = Double.toString(masterclass.getPrijs());
        TextField_Prijs.setText(prijs);
        
        Datum = masterclass.getDatum();
        java.util.Calendar cal = java.util.Calendar.getInstance();
            cal.clear();
            cal.setTime(Datum);
            jaar = cal.get(Calendar.YEAR);
            maand = cal.get(Calendar.MONTH);
            dag = cal.get(Calendar.DAY_OF_MONTH);
            maand++;

            String JAAR = Integer.toString(jaar);
            String MAAND = Integer.toString(maand);
            String DAG = Integer.toString(dag);

            TextField_Jaar.setText(JAAR);
            TextField_Maand.setText(MAAND);
            TextField_Dag.setText(DAG);
            
         String minimale_rating = Integer.toString(masterclass.getRating());
         TextField_Minimalerating.setText(minimale_rating);
         
        
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        TextField_Minimalerating = new javax.swing.JTextField();
        TextField_Prijs = new javax.swing.JTextField();
        Button_Wijzigen = new javax.swing.JButton();
        Button_Back = new javax.swing.JButton();
        ComboBox_Locatie = new javax.swing.JComboBox();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        ComboBox_Docent = new javax.swing.JComboBox();
        TextField_Jaar = new javax.swing.JTextField();
        TextField_Dag = new javax.swing.JTextField();
        TextField_Maand = new javax.swing.JTextField();
        Label_Docent = new javax.swing.JLabel();
        Label_Locatie = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        Button_Wijzigen.setText("Wijzigen");
        Button_Wijzigen.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Button_WijzigenActionPerformed(evt);
            }
        });

        Button_Back.setText("Back");
        Button_Back.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Button_BackActionPerformed(evt);
            }
        });

        ComboBox_Locatie.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        ComboBox_Locatie.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ComboBox_LocatieActionPerformed(evt);
            }
        });

        jLabel2.setText("Datum (DD-MM-JJJJ)");

        jLabel3.setText("Locatie");

        jLabel6.setText("Prijs");

        jLabel7.setText("Minimale rating");

        jLabel5.setText("Docent");

        ComboBox_Docent.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        ComboBox_Docent.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ComboBox_DocentActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel2)
                    .addComponent(Button_Back)
                    .addComponent(jLabel6)
                    .addComponent(jLabel7)
                    .addComponent(jLabel5)
                    .addComponent(jLabel3))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGap(29, 29, 29)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(TextField_Minimalerating, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 89, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(ComboBox_Locatie, javax.swing.GroupLayout.Alignment.TRAILING, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(ComboBox_Docent, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(Label_Docent, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(Label_Locatie, javax.swing.GroupLayout.PREFERRED_SIZE, 76, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(76, 76, 76)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(TextField_Prijs, javax.swing.GroupLayout.PREFERRED_SIZE, 89, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(Button_Wijzigen, javax.swing.GroupLayout.PREFERRED_SIZE, 89, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(TextField_Dag, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(TextField_Maand, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(TextField_Jaar)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(TextField_Dag, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(TextField_Maand, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(TextField_Jaar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(TextField_Prijs, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel6))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(TextField_Minimalerating, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel7))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel5)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jLabel3))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(ComboBox_Docent, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(Label_Docent, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(ComboBox_Locatie, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(Label_Locatie, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(Button_Back)
                    .addComponent(Button_Wijzigen))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void Button_BackActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Button_BackActionPerformed
        new MasterclassBeheer().setVisible(true);
        this.dispose();
    }//GEN-LAST:event_Button_BackActionPerformed

    private void Button_WijzigenActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Button_WijzigenActionPerformed
        Docent = comboBoxSelectedValueDocent();
        Locatie = comboBoxSelectedValueLocatie();
        
        try{
        Prijs = Double.parseDouble(TextField_Prijs.getText());
        Minimale_rating = Integer.parseInt(TextField_Minimalerating.getText());
        
        Datum = null;
        
            dag = Integer.parseInt(TextField_Dag.getText());
            maand = Integer.parseInt(TextField_Maand.getText());
            jaar = Integer.parseInt(TextField_Jaar.getText());
            
            Datum = DateUtil.toSqlDate(jaar, maand, dag);
        }catch(NumberFormatException e){
            JOptionPane.showMessageDialog(this, "Voer de velden correct in.");
        }
        

        
        
        Minimale_rating = Integer.parseInt(TextField_Minimalerating.getText());
        try {
                String sql = "update masterclass set Prijs = ?, Datum = ?, Minimale_rating = ?, Docent = ?, Vindt_plaats_in = ? where M_Code = ?";
                Connection conn = SimpleDataSourceV2.getConnection();
                PreparedStatement stat = conn.prepareStatement(sql);
                stat.setDouble(1, Prijs);
                stat.setDate(2, Datum);
                stat.setInt(3, Minimale_rating);
                stat.setInt(4, Docent);
                stat.setInt(5, Locatie);
                stat.setInt(6, M_Code);
                
                stat.execute();
                
                this.dispose();
                new MasterclassBeheer().setVisible(true);
            }catch (SQLException ex) {
                JOptionPane.showMessageDialog(this, "Databasefout" + ex.toString());
            }
    }//GEN-LAST:event_Button_WijzigenActionPerformed

    private void ComboBox_DocentActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ComboBox_DocentActionPerformed
        int d_code = comboBoxSelectedValueDocent();
        
        try {
            Connection conn = SimpleDataSourceV2.getConnection();
            String sql = "select Achternaam from deelnemer where D_Code = ?";
            PreparedStatement stat = conn.prepareStatement(sql);
            stat.setInt(1,d_code);
            ResultSet resultSet = stat.executeQuery();
            
            while(resultSet.next()){
                Achternaam = resultSet.getString("Achternaam");
            }
            
            Label_Docent.setText(Achternaam);
    }catch(SQLException e)
    {
        JOptionPane.showMessageDialog(this, e);
    }
    }//GEN-LAST:event_ComboBox_DocentActionPerformed

    private void ComboBox_LocatieActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ComboBox_LocatieActionPerformed
        int f_code = comboBoxSelectedValueLocatie();
        
        try {
            Connection conn = SimpleDataSourceV2.getConnection();
            String sql = "select Naam from faciliteit where F_Code = ?";
            PreparedStatement stat = conn.prepareStatement(sql);
            stat.setInt(1,f_code);
            ResultSet resultSet = stat.executeQuery();
            
            while(resultSet.next()){
                LNaam = resultSet.getString("Naam");
            }
            
            Label_Locatie.setText(LNaam);
    }catch(SQLException e)
    {
        JOptionPane.showMessageDialog(this, e);
    }
    }//GEN-LAST:event_ComboBox_LocatieActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /*
         * Set the Nimbus look and feel
         */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /*
         * If Nimbus (introduced in Java SE 6) is not available, stay with the
         * default look and feel. For details see
         * http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(MasterclassWijzigen.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(MasterclassWijzigen.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(MasterclassWijzigen.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(MasterclassWijzigen.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /*
         * Create and display the form
         */
        java.awt.EventQueue.invokeLater(new Runnable() {

            public void run() {
                new MasterclassWijzigen().setVisible(true);
            }
        });
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton Button_Back;
    private javax.swing.JButton Button_Wijzigen;
    private javax.swing.JComboBox ComboBox_Docent;
    private javax.swing.JComboBox ComboBox_Locatie;
    private javax.swing.JLabel Label_Docent;
    private javax.swing.JLabel Label_Locatie;
    private javax.swing.JTextField TextField_Dag;
    private javax.swing.JTextField TextField_Jaar;
    private javax.swing.JTextField TextField_Maand;
    private javax.swing.JTextField TextField_Minimalerating;
    private javax.swing.JTextField TextField_Prijs;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    // End of variables declaration//GEN-END:variables


   

    private void vulDocent() {
        DefaultComboBoxModel docent = new DefaultComboBoxModel();
        try {
            Connection conn = SimpleDataSourceV2.getConnection();
            String sql = "select D_Code from deelnemer where is_bekend = 'j'";
            PreparedStatement stat = conn.prepareStatement(sql);
            
            ResultSet resultSet = stat.executeQuery();
            
            while(resultSet.next()){
                Docent = resultSet.getInt("D_Code");
                docent.addElement(Docent);
            }
            
            ComboBox_Docent.setModel(docent);
    }catch(SQLException e)
    {
        JOptionPane.showMessageDialog(this, e);
    }
    }

    private void vulLocatie() {
        DefaultComboBoxModel locatie = new DefaultComboBoxModel();
        try {
            Connection conn = SimpleDataSourceV2.getConnection();
            String sql = "select F_Code from faciliteit";
            PreparedStatement stat = conn.prepareStatement(sql);
            
            ResultSet resultSet = stat.executeQuery();
            
            while(resultSet.next()){
                Locatie = resultSet.getInt("F_Code");
                locatie.addElement(Locatie);
            }
            
            ComboBox_Locatie.setModel(locatie);
    }catch(SQLException e)
    {
        JOptionPane.showMessageDialog(this, e);
    }
    }
    
    private int comboBoxSelectedValueDocent()
    {
        int selectedItem = 0;
        Object selected = ComboBox_Docent.getSelectedItem();
        if (selected != null)
        {
            String selectedItemStr = selected.toString();
            selectedItem = Integer.parseInt(selectedItemStr);
        }
        return selectedItem;
    }
    
    private int comboBoxSelectedValueLocatie()
    {
        int selectedItem = 0;
        Object selected = ComboBox_Locatie.getSelectedItem();
        if (selected != null)
        {
            String selectedItemStr = selected.toString();
            selectedItem = Integer.parseInt(selectedItemStr);
        }
        return selectedItem;
    }
}
