/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
package GUI;

import configuration.SimpleDataSourceV2;
import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import javax.swing.DefaultComboBoxModel;
import javax.swing.JOptionPane;
import java.sql.Date;
import utils.DateUtil;

/**
 *
 * @author Otto
 */
public class MasterclassToevoegen extends javax.swing.JFrame {
int M_Code;
int Niveau;
int Prijs;
Date Datum;
int Docent;
int Locatie;
String Achternaam;
String LNaam;

    /**
     * Creates new form MasterclassToevoegen
     */
    public MasterclassToevoegen() {
        initComponents();
        vulDocent();
        vulLocatie();

    }


    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        TextField_Niveau = new javax.swing.JTextField();
        TextField_Dag = new javax.swing.JTextField();
        Button_Toevoegen = new javax.swing.JButton();
        Button_Back = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        TextField_Prijs = new javax.swing.JTextField();
        TextField_Minimalerating = new javax.swing.JTextField();
        TextField_Maand = new javax.swing.JTextField();
        TextField_Jaar = new javax.swing.JTextField();
        Label_Docent = new javax.swing.JLabel();
        Label_Locatie = new javax.swing.JLabel();
        ComboBox_Locatie = new javax.swing.JComboBox();
        ComboBox_Docent = new javax.swing.JComboBox();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel2.setText("Datum (DD-MM-JJJJ)");

        jLabel3.setText("Locatie");

        Button_Toevoegen.setText("Toevoegen");
        Button_Toevoegen.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Button_ToevoegenActionPerformed(evt);
            }
        });

        Button_Back.setText("Back");
        Button_Back.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Button_BackActionPerformed(evt);
            }
        });

        jLabel1.setText("Niveau");

        jLabel5.setText("Docent");

        jLabel6.setText("Prijs");

        jLabel7.setText("Minimale rating");

        TextField_Prijs.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                TextField_PrijsActionPerformed(evt);
            }
        });

        ComboBox_Locatie.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        ComboBox_Locatie.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ComboBox_LocatieActionPerformed(evt);
            }
        });

        ComboBox_Docent.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        ComboBox_Docent.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ComboBox_DocentActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(Button_Back)
                            .addComponent(jLabel1)
                            .addComponent(jLabel2)
                            .addComponent(jLabel3)
                            .addComponent(jLabel5))
                        .addGap(10, 10, 10)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(TextField_Prijs, javax.swing.GroupLayout.PREFERRED_SIZE, 89, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(TextField_Minimalerating, javax.swing.GroupLayout.PREFERRED_SIZE, 89, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(ComboBox_Locatie, javax.swing.GroupLayout.Alignment.TRAILING, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(ComboBox_Docent, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(Label_Docent, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(Label_Locatie, javax.swing.GroupLayout.PREFERRED_SIZE, 76, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addComponent(Button_Toevoegen, javax.swing.GroupLayout.PREFERRED_SIZE, 89, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(TextField_Dag, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(TextField_Niveau, javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(TextField_Maand, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                        .addComponent(TextField_Jaar, javax.swing.GroupLayout.PREFERRED_SIZE, 72, javax.swing.GroupLayout.PREFERRED_SIZE))))))
                    .addComponent(jLabel7)
                    .addComponent(jLabel6))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(TextField_Niveau, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel1))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(TextField_Dag, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel2)
                    .addComponent(TextField_Maand, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(TextField_Jaar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(TextField_Prijs, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel6))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(TextField_Minimalerating, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel7))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(ComboBox_Docent, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jLabel5))
                    .addComponent(Label_Docent, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(ComboBox_Locatie, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jLabel3))
                    .addComponent(Label_Locatie, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(Button_Toevoegen)
                    .addComponent(Button_Back))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void Button_ToevoegenActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Button_ToevoegenActionPerformed
        try{
        Niveau = Integer.parseInt(TextField_Niveau.getText());
        Prijs = Integer.parseInt(TextField_Prijs.getText());
        
        Datum = null;
        
            int dag = Integer.parseInt(TextField_Dag.getText());
            int maand = Integer.parseInt(TextField_Maand.getText());
            int jaar = Integer.parseInt(TextField_Jaar.getText());
            
            Datum = DateUtil.toSqlDate(jaar, maand, dag);
        }catch(NumberFormatException e){
            JOptionPane.showMessageDialog(this, "Voer de velden correct in.");
        }
        
        Docent = comboBoxSelectedValueDocent();
        Locatie = comboBoxSelectedValueLocatie();
        
        int Minimale_rating = Integer.parseInt(TextField_Minimalerating.getText());
        try {
                String sql = "insert into masterclass (Niveau, Prijs, Datum, Minimale_rating, Docent, Vindt_plaats_in) values (?,?,?,?,?,?)";
                Connection conn = SimpleDataSourceV2.getConnection();
                PreparedStatement stat = conn.prepareStatement(sql);
                stat.setInt(1, Niveau);
                stat.setInt(2, Prijs);
                stat.setDate(3, Datum);
                stat.setInt(4, Minimale_rating);
                stat.setInt(5, Docent);
                stat.setInt(6, Locatie);
                
                stat.execute();
                
                this.dispose();
                new MasterclassBeheer().setVisible(true);
            }catch (SQLException ex) {
                JOptionPane.showMessageDialog(this, "Databasefout" + ex.toString());
            }
    
    }//GEN-LAST:event_Button_ToevoegenActionPerformed

    private void Button_BackActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Button_BackActionPerformed
        new MasterclassBeheer().setVisible(true);
        this.dispose();
        
    }//GEN-LAST:event_Button_BackActionPerformed

    private void ComboBox_LocatieActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ComboBox_LocatieActionPerformed
        int f_code = comboBoxSelectedValueLocatie();

        try {
            Connection conn = SimpleDataSourceV2.getConnection();
            String sql = "select Naam from faciliteit where F_Code = ?";
            PreparedStatement stat = conn.prepareStatement(sql);
            stat.setInt(1, f_code);
            ResultSet resultSet = stat.executeQuery();

            while (resultSet.next()) {
                LNaam = resultSet.getString("Naam");
            }

            Label_Locatie.setText(LNaam);
        } catch (SQLException e) {
            JOptionPane.showMessageDialog(this, e);
        }
    }//GEN-LAST:event_ComboBox_LocatieActionPerformed

    private void ComboBox_DocentActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ComboBox_DocentActionPerformed
        int d_code = comboBoxSelectedValueDocent();

        try {
            Connection conn = SimpleDataSourceV2.getConnection();
            String sql = "select Achternaam from deelnemer where D_Code = ?";
            PreparedStatement stat = conn.prepareStatement(sql);
            stat.setInt(1, d_code);
            ResultSet resultSet = stat.executeQuery();

            while (resultSet.next()) {
                Achternaam = resultSet.getString("Achternaam");
            }

            Label_Docent.setText(Achternaam);
        } catch (SQLException e) {
            JOptionPane.showMessageDialog(this, e);
        }
    }//GEN-LAST:event_ComboBox_DocentActionPerformed

    private void TextField_PrijsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_TextField_PrijsActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_TextField_PrijsActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /*
         * Set the Nimbus look and feel
         */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /*
         * If Nimbus (introduced in Java SE 6) is not available, stay with the
         * default look and feel. For details see
         * http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(MasterclassToevoegen.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(MasterclassToevoegen.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(MasterclassToevoegen.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(MasterclassToevoegen.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /*
         * Create and display the form
         */
        java.awt.EventQueue.invokeLater(new Runnable() {

            public void run() {
                new MasterclassToevoegen().setVisible(true);
            }
        });
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton Button_Back;
    private javax.swing.JButton Button_Toevoegen;
    private javax.swing.JComboBox ComboBox_Docent;
    private javax.swing.JComboBox ComboBox_Locatie;
    private javax.swing.JLabel Label_Docent;
    private javax.swing.JLabel Label_Locatie;
    private javax.swing.JTextField TextField_Dag;
    private javax.swing.JTextField TextField_Jaar;
    private javax.swing.JTextField TextField_Maand;
    private javax.swing.JTextField TextField_Minimalerating;
    private javax.swing.JTextField TextField_Niveau;
    private javax.swing.JTextField TextField_Prijs;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    // End of variables declaration//GEN-END:variables

    private void vulDocent() {
        DefaultComboBoxModel docent = new DefaultComboBoxModel();
        try {
            Connection conn = SimpleDataSourceV2.getConnection();
            String sql = "select D_Code from deelnemer where is_bekend = 'j'";
            PreparedStatement stat = conn.prepareStatement(sql);
            
            ResultSet resultSet = stat.executeQuery();
            
            while(resultSet.next()){
                Docent = resultSet.getInt("D_Code");
                docent.addElement(Docent);
            }
            
            ComboBox_Docent.setModel(docent);
    }catch(SQLException e)
    {
        JOptionPane.showMessageDialog(this, e);
    }
    }

    private void vulLocatie() {
        DefaultComboBoxModel locatie = new DefaultComboBoxModel();
        try {
            Connection conn = SimpleDataSourceV2.getConnection();
            String sql = "select F_Code from faciliteit";
            PreparedStatement stat = conn.prepareStatement(sql);
            
            ResultSet resultSet = stat.executeQuery();
            
            while(resultSet.next()){
                Locatie = resultSet.getInt("F_Code");
                locatie.addElement(Locatie);
            }
            
            ComboBox_Locatie.setModel(locatie);
    }catch(SQLException e)
    {
        JOptionPane.showMessageDialog(this, e);
    }
    }
    
    private int comboBoxSelectedValueDocent()
    {
        int selectedItem = 0;
        Object selected = ComboBox_Docent.getSelectedItem();
        if (selected != null)
        {
            String selectedItemStr = selected.toString();
            selectedItem = Integer.parseInt(selectedItemStr);
        }
        return selectedItem;
    }
    
    private int comboBoxSelectedValueLocatie()
    {
        int selectedItem = 0;
        Object selected = ComboBox_Locatie.getSelectedItem();
        if (selected != null)
        {
            String selectedItemStr = selected.toString();
            selectedItem = Integer.parseInt(selectedItemStr);
        }
        return selectedItem;
    }
}
